newset={1,2,3,4,8,7,0}
pop_item=newset.pop()
print(pop_item)
print(newset)
newset.add(9)
print ("newset after add = ",newset)
nayVal=newset.remove(2)
newset1=newset.copy()
print(newset1)
print(newset1 is newset)
print(newset1.update([10,11,12]))
print(newset1)
print(nayVal)
isVal=newset.discard(2)
print(isVal)
newset_to_frozenset=frozenset(newset)
print(newset_to_frozenset)
print(type(newset_to_frozenset))